# 生产环境配置
environment: production
debug: false
host: "0.0.0.0"
port: 8080

database:
  path: "/var/lib/td_stock/stock_data.db"
  max_connections: 20
  timeout: 30.0
  backup_enabled: true
  backup_interval: 1800  # 30分钟

api:
  tushare_token: null  # 从环境变量 TUSHARE_TOKEN 获取
  rate_limit_per_minute: 199
  timeout: 30.0
  retry_times: 5
  retry_delay: 2.0

cache:
  enabled: true
  directory: "/var/cache/td_stock"
  default_ttl: 1800  # 30分钟
  max_size_mb: 1000
  cleanup_interval: 3600

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "/var/log/td_stock/app.log"
  max_file_size: 52428800  # 50MB
  backup_count: 10
  console_output: false

security:
  secret_key: null  # 从环境变量 SECRET_KEY 获取
  session_timeout: 1800
  max_request_size: 8388608  # 8MB
  rate_limit_enabled: true
  cors_enabled: false
  allowed_origins: ["https://yourdomain.com"]